### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sekikn**
* Update the examples so that users can try them easily

* Add note about Guava and Protobuf version mismatch

* Fix minor typos

### CODE REVIEW

**Comment by sekikn** [comment]
Hi @maropu, thank you for developing this useful plugin! It took some trial and error to use it, so I'd like to reflect it to the README.

I also would like to describe the problems I came across and their workaround here, as it might be useful for other users.

----

First, I downloaded Spark binary distribution and installed it to the local environment.

```
$ curl -sLO https://downloads.apache.org/spark/spark-3.0.3/spark-3.0.3-bin-hadoop2.7.tgz
$ tar xf spark-3.0.3-bin-hadoop2.7.tgz
$ export SPARK_HOME=$(pwd)/spark-3.0.3-bin-hadoop2.7
```

Then I cloned this repository and saved the MapDB file with it.

```
$ git clone https://github.com/maropu/spark-executor-dict-plugin.git
$ cd spark-executor-dict-plugin
$ $SPARK_HOME/bin/spark-shell --jars=./assembly/spark-executor-dict-plugin_2.12_spark3.0-0.1.0-SNAPSHOT-with-dependencies.jar

...

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.3
      /_/
         
Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_292)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import io.github.maropu.MapDbConverter
import io.github.maropu.MapDbConverter

scala> val largeMap = Map("key1" -> "value1", "key2" -> "value2")
largeMap: scala.collection.immutable.Map[String,String] = Map(key1 -> value1, key2 -> value2)

scala> MapDbConverter.save("/tmp/largeMap.db", largeMap)

scala> :quit
```

Next I launched pyspark with this plugin, but it failed with a `NoClassDefFoundError`.

```
$ $SPARK_HOME/bin/pyspark --jars=./assembly/spark-executor-dict-plugin_2.12_spark3.0-0.1.0-SNAPSHOT-with-dependencies.jar --conf spark.plugins=org.apache.spark.plugin.SparkExecutorDictPlugin --conf spark.files=/tmp/largeMap.db

...

/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/shell.py:45: UserWarning: Failed to initialize Spark session.
  warnings.warn("Failed to initialize Spark session.")
Traceback (most recent call last):
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/shell.py", line 41, in <module>
    spark = SparkSession._create_shell_session()
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/sql/session.py", line 492, in _create_shell_session
    return SparkSession.builder.getOrCreate()
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/sql/session.py", line 186, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/context.py", line 378, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/context.py", line 135, in __init__
    self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/context.py", line 198, in _do_init
    self._jsc = jsc or self._initialize_context(self._conf._jconf)
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/pyspark/context.py", line 317, in _initialize_context
    return self._jvm.JavaSparkContext(jconf)
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1568, in __call__
    return_value = get_return_value(
  File "/home/sekikn/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:40)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:25)
	at io.grpc.ServerBuilder.forPort(ServerBuilder.java:44)
	at org.apache.spark.plugin.grpc.DictServer.<init>(dict.scala:62)
	at org.apache.spark.plugin.SparkExecutorDictPlugin$$anon$2.init(SparkExecutorDictPlugin.scala:101)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:111)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:99)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:164)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:152)
	at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:234)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:221)
	at org.apache.spark.executor.Executor.<init>(Executor.scala:234)
	at org.apache.spark.scheduler.local.LocalEndpoint.<init>(LocalSchedulerBackend.scala:64)
	at org.apache.spark.scheduler.local.LocalSchedulerBackend.start(LocalSchedulerBackend.scala:132)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:201)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:562)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

I also tried spark-shell instead of pyspark, but I got a `NoSuchMethodError`.

```
$ $SPARK_HOME/bin/spark-shell --jars=./assembly/spark-executor-dict-plugin_2.12_spark3.0-0.1.0-SNAPSHOT-with-dependencies.jar --py-files ./assembly/dict.zip --conf spark.plugins=org.apache.spark.plugin.SparkExecutorDictPlugin --conf spark.files=/tmp/largeMap.db

...

java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
  at io.grpc.Metadata$Key.validateName(Metadata.java:742)
  at io.grpc.Metadata$Key.<init>(Metadata.java:750)
  at io.grpc.Metadata$Key.<init>(Metadata.java:668)
  at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
  at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
  at io.grpc.Metadata$Key.of(Metadata.java:705)
  at io.grpc.Metadata$Key.of(Metadata.java:701)
  at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:81)
  at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:79)
  at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:83)
  at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:40)
  at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:25)
  at io.grpc.ServerBuilder.forPort(ServerBuilder.java:44)
  at org.apache.spark.plugin.grpc.DictServer.<init>(dict.scala:62)
  at org.apache.spark.plugin.SparkExecutorDictPlugin$$anon$2.init(SparkExecutorDictPlugin.scala:101)
  at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:111)
  at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
  at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
  at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:99)
  at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:164)
  at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:152)
  at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:234)
  at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:221)
  at org.apache.spark.executor.Executor.<init>(Executor.scala:234)
  at org.apache.spark.scheduler.local.LocalEndpoint.<init>(LocalSchedulerBackend.scala:64)
  at org.apache.spark.scheduler.local.LocalSchedulerBackend.start(LocalSchedulerBackend.scala:132)
  at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:201)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:562)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2589)
  at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:937)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:931)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:106)
  ... 55 elided
<console>:14: error: not found: value spark
       import spark.implicits._
              ^
<console>:14: error: not found: value spark
       import spark.sql
              ^
```

That error seemed to be caused by the version mismatch of Guava. [gRPC-Java 1.39.0 depends on Guava 30.1-android and Protocol buffers 3.17.2](https://github.com/grpc/grpc-java/blob/master/build.gradle#L58), so I tried to align all jars with it.
First, I rebuilt the plugin with that version of Guava.

```
$ mvn clean package -Dguava.version=30.1-android

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.575 s
[INFO] Finished at: 2021-08-19T09:29:54+09:00
[INFO] ------------------------------------------------------------------------
```

Then I replaced Spark jars with those versions.

```
$ mv $SPARK_HOME/jars/guava-14.0.1.jar ~
$ cp ~/.m2/repository/com/google/guava/guava/30.1-android/guava-30.1-android.jar $SPARK_HOME/jars
$ cp ~/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar $SPARK_HOME/jars

$ mv $SPARK_HOME/jars/protobuf-java-2.5.0.jar ~
$ cp ~/.m2/repository/com/google/protobuf/protobuf-java/3.17.2/protobuf-java-3.17.2.jar $SPARK_HOME/jars
```

In addition to them, this plugin seemed to require the grpcio and google-api-python-client packages when called via pyspark, so I also installed them.

```
$ pip3 install grpcio==1.39.0 google-api-python-client

...

Successfully installed cachetools-4.2.2 certifi-2021.5.30 charset-normalizer-2.0.4 google-api-core-2.0.0 google-api-python-client-2.17.0 google-auth-2.0.0 google-auth-httplib2-0.1.0 googleapis-common-protos-1.53.0 grpcio-1.39.0 httplib2-0.19.1 idna-3.2 protobuf-3.17.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-2.4.7 requests-2.26.0 rsa-4.7.2 uritemplate-3.0.1 urllib3-1.26.6
```

With the preparation described above, I finally succeeded to run this plugin.

```
$ $SPARK_HOME/bin/pyspark --jars=./assembly/spark-executor-dict-plugin_2.12_spark3.0-0.1.0-SNAPSHOT-with-dependencies.jar --py-files ./assembly/dict.zip --conf spark.plugins=org.apache.spark.plugin.SparkExecutorDictPlugin --conf spark.files=/tmp/largeMap.db
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 

...

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.0.3
      /_/

Using Python version 3.8.10 (default, Jun  2 2021 10:49:15)
SparkSession available as 'spark'.
>>> def udf(x):
...     from client import DictClient
...     hmap = DictClient()
...     value = hmap.lookup(x)
...     return value
... 
>>> spark.udf.register("udf", udf)
<function udf at 0x7f85a5196040>
>>> spark.sql("SELECT udf('key1')").show()
+---------+                                                                     
|udf(key1)|
+---------+
|   value1|
+---------+
```

**Comment by maropu** [comment]
You've tried it on spark-v3.1? If the same issue can happen, this update seems fine.
```
$ curl -sLO https://downloads.apache.org/spark/spark-3.0.3/spark-3.0.3-bin-hadoop2.7.tgz
```

**Comment by maropu** [comment]
>> this plugin seemed to require the grpcio and google-api-python-client packages

Is it true? It seems to work fine w/o `google-api-python-client`. How I checked it is as follows;
```
$ cat ./bin/conda.yml
# Generated by 'conda env export > conda.yml'
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - pyspark=3.1.2
  - pyarrow=1.0.0
  - grpcio=1.35.0
  - grpcio-tools=1.35.0
  - mypy=0.790
  - flake8=3.8.4

$ conda env create -f ./bin/conda.yml --name dict-plugin-test python=3.6
$ conda activate dict-plugin-test
$ conda env export
name: dict-plugin-test
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20200225.2=hb1e8313_2
  - arrow-cpp=1.0.0=py36h1234567_2_cpu
  - aws-sdk-cpp=1.7.164=h2d5dea0_2
  - brotli=1.0.9=h0d85af4_5
  - brotli-bin=1.0.9=h0d85af4_5
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.2=h0d85af4_0
  - ca-certificates=2021.5.30=h033912b_0
  - curl=7.78.0=hb861fe1_0
  - flake8=3.8.4=py_0
  - gflags=2.2.2=hb1e8313_1004
  - glog=0.4.0=hb7f4fc5_3
  - grpc-cpp=1.30.2=h1622386_0
  - grpcio=1.35.0=py36hb31a93b_0
  - grpcio-tools=1.35.0=py36h23ab428_1
  - importlib-metadata=4.6.4=py36h79c6626_0
  - krb5=1.19.2=hcfbf3a7_0
  - libblas=3.9.0=11_osx64_openblas
  - libbrotlicommon=1.0.9=h0d85af4_5
  - libbrotlidec=1.0.9=h0d85af4_5
  - libbrotlienc=1.0.9=h0d85af4_5
  - libcblas=3.9.0=11_osx64_openblas
  - libcurl=7.78.0=hf45b732_0
  - libcxx=12.0.1=habf9029_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=hddc9c9b_3
  - libffi=3.2.1=hb1e8313_1007
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - liblapack=3.9.0=11_osx64_openblas
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.17=openmp_h3351f45_1
  - libprotobuf=3.12.4=hab81aa3_0
  - libssh2=1.9.0=h52ee1ee_6
  - libthrift=0.13.0=h8459986_6
  - libutf8proc=2.6.1=h35c211d_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.2=hb1e8313_3
  - mccabe=0.6.1=py_1
  - mypy=0.790=py_0
  - mypy_extensions=0.4.3=py36h79c6626_3
  - ncurses=6.2=h2e338ed_4
  - numpy=1.19.5=py36h08b5fde_2
  - openssl=1.1.1k=h0d85af4_1
  - pandas=1.1.5=py36h2be6da3_0
  - parquet-cpp=1.5.1=2
  - pip=21.2.4=pyhd8ed1ab_0
  - protobuf=3.12.4=py36h27176af_0
  - psutil=5.8.0=py36hfa26744_1
  - py4j=0.10.9=pyh9f0ad1d_0
  - pyarrow=1.0.0=py36h1234567_2_cpu
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pyspark=3.1.2=pyh6c4a22f_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.1=pyhd8ed1ab_0
  - re2=2020.08.01=hb1e8313_1
  - readline=7.0=hcfe32e1_1001
  - setuptools=57.4.0=py36h79c6626_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=hb1e8313_3
  - sqlite=3.28.0=h9721f7c_0
  - thrift-compiler=0.13.0=h8459986_6
  - thrift-cpp=0.13.0=6
  - tk=8.6.10=h0419947_1
  - typed-ast=1.4.3=py36hfa26744_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=haf1e3a3_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.8=h62961b2_0

$ CONDA_DISABLED=1 ./bin/run-tests
starting python compilation test...
python compilation succeeded.

starting pycodestyle test...
pycodestyle checks passed.

starting flake8 test...
flake8 checks passed.

starting mypy test...
mypy checks passed.


all lint-python tests passed!
Running PySpark tests. Output is in /Users/maropu/Repositories/spark/spark-executor-dict-plugin/bin/unit-tests.log
Will test against the following Python executables: ['python3.6']
python3.6 python_implementation is CPython
python3.6 version is: Python 3.6.8 :: Anaconda, Inc.
Starting test(python3.6): tests.test_dict
Finished test(python3.6): tests.test_dict (31s)
Tests passed in 31 seconds
```

**Comment by maropu** [comment]
@sekikn I checked the dependency again and I shaded Guava/Protobuf, see the commit: https://github.com/maropu/spark-executor-dict-plugin/commit/8cc169933ecfbdbe27d676bda4a0a68f02be4945
As far as I checked, the issue goes away, so could you check it again?

**Comment by sekikn** [comment]
> You've tried it on spark-v3.1?

No, I used the spark-3.0 branch when I wrote the above comment. I'll try again with the spark-3.1 branch and Spark 3.1.x. Thanks!

> Is it true? It seems to work fine w/o google-api-python-client.

Hmm, it may have been my misunderstanding. I'll check it again on the next try.

> I checked the dependency again and I shaded Guava/Protobuf

I really appreciate that! I'll try the latest version and update my PR in accordance with the result.

**Comment by sekikn** [comment]
I confirmed the latest version of the spark-3.1 branch worked as expected, without Guava version mismatch. I'll update the PR soon.

----

Download and install Spark 3.1:

```
$ curl -sLO https://downloads.apache.org/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz
$ tar xf spark-3.1.2-bin-hadoop2.7.tgz 
$ export SPARK_HOME=$(pwd)/spark-3.1.2-bin-hadoop2.7
```

Clone the repository of this plugin:

```
$ git clone -q https://github.com/maropu/spark-executor-dict-plugin.git
$ cd spark-executor-dict-plugin
$ git branch 
* spark-3.1
```

Create and save data into MapDB:

```
$ $SPARK_HOME/bin/spark-shell --jars ./assembly/spark-executor-dict-plugin_2.12_spark3.1-0.1.0-SNAPSHOT-with-dependencies.jar 

...

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/
         
Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_292)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import io.github.maropu.MapDbConverter
import io.github.maropu.MapDbConverter

scala> val largeMap = Map("key1" -> "value1", "key2" -> "value2")
largeMap: scala.collection.immutable.Map[String,String] = Map(key1 -> value1, key2 -> value2)

scala> MapDbConverter.save("/tmp/largeMap.db", largeMap)

scala> :quit
```

Install python dependencies (I used venv and pip instead of conda):

```
$ python3 -m venv /tmp/venv
$ . /tmp/venv/bin/activate
$ pip3 install -r bin/requirements.txt 

...

Installing collected packages: py4j, pyspark, numpy, pyarrow, six, grpcio, protobuf, grpcio-tools, typed-ast, mypy-extensions, typing-extensions, mypy, mccabe, pycodestyle, pyflakes, flake8
Successfully installed flake8-3.8.4 grpcio-1.35.0 grpcio-tools-1.35.0 mccabe-0.6.1 mypy-0.790 mypy-extensions-0.4.3 numpy-1.21.2 protobuf-3.17.3 py4j-0.10.9 pyarrow-1.0.0 pycodestyle-2.6.0 pyflakes-2.2.0 pyspark-3.1.2 six-1.16.0 typed-ast-1.4.3 typing-extensions-3.10.0.0
```

Run example script:

```
$ $SPARK_HOME/bin/pyspark --jars ./assembly/spark-executor-dict-plugin_2.12_spark3.1-0.1.0-SNAPSHOT-with-dependencies.jar --py-files ./assembly/dict.zip --conf spark.plugins=org.apache.spark.plugin.SparkExecutorDictPlugin --conf spark.files=/tmp/largeMap.db

...

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/

Using Python version 3.8.10 (default, Jun  2 2021 10:49:15)
Spark context Web UI available at http://192.168.2.2:4040
Spark context available as 'sc' (master = local[*], app id = local-1629421994001).
SparkSession available as 'spark'.
>>> def udf(x):
...   from client import DictClient
...   hmap = DictClient()
...   value = hmap.lookup(x)
...   return value
... 
>>> spark.udf.register("udf", udf)
<function udf at 0x7fb6c50aeaf0>
>>> spark.sql("SELECT udf('key1')").show()
+---------+                                                                     
|udf(key1)|
+---------+
|   value1|
+---------+
```

**Comment by maropu** [comment]
LGTM

**Comment by maropu** [comment]
NOTE: merged to spark-3.1/3.0.

**Pull request merged**
